### ISSUE TITLE
Model comparison not saving results?

### ISSUE THREAD

**Issue by zhexingli** [California-Planet-Search/radvel#326] opened 2020-09-12 00:55 UTC
Hello,

I'm not sure why but this one time model comparions doesn't seem to save the results? When I try to produce a radvel report, it says this:

> WARNING: Could not find ic model comparison in ./HD140901_radvel/HD140901_radvel_radvel.stat.
Please make sure that you have run `radvel ic -t ic` (or, e.g., `radvel ic -t nplanets e trend jit gp`)
if you would like to include the model comparison table in the report.

Even though I did type the model comparison command in before generating the report:

`radvel ic -t nplanets e trend jit -s HD140901_radvel.py`

Why is this happening?

**Comment by zhexingli** [comment] 2020-09-12 00:59
nvm, very stupid of me. This was only a one-planet fit, no need to include 'nplanets' in the model comparison. Leaving 'nplanets' out it's all good again.

**Comment by zhexingli** [comment] 2020-09-19 02:35
Sry, I had to reopen it. I'm not sure, is there an issue with model comparison with 'nplanets'? Whenever I include 'nplanets' in the command "radvel ic -t xxx xxx -s [file]", doesn't matter if only doing number of planets comparison or together with other variables, my radvel returns error message when I do 'radvel report -s [file]':

> WARNING: Could not find ic model comparison in ./HD134987_radvel/HD134987_radvel_radvel.stat.
Please make sure that you have run `radvel ic -t ic` (or, e.g., `radvel ic -t nplanets e trend jit gp`)
if you would like to include the model comparison table in the report.

I don't seem to get any warnings when doing report if I only do model comparison with other parameters such as 'e', 'trend', 'jit', or all together but without 'nplanets'.

**Comment by bjfultn** [comment] 2020-09-22 23:17
OK, send the config file and data and I'll try to reproduce this behavior.

**Comment by zhexingli** [comment] 2020-09-22 23:35
Thanks BJ. Here're the files packed in zip
[Files.zip](https://github.com/California-Planet-Search/radvel/files/5264572/Files.zip)

I have a feeling that the error message pops up at times when doing 'nplanets' comparison on data where all signals are significant. But sometimes it's hard to tell if they're all really significant...

**Comment by bjfultn** [comment] 2020-09-23 00:17
This bug comes up because there are nan values in the particular ic comparison table. I've fixed this to allow for those bad values more gracefully in PR #388 which will be released as v1.4.2 shortly.

**Closed by bjfultn** 2020-09-23 00:17 UTC

**Comment by zhexingli** [comment] 2020-09-23 00:21
Awesome, thank you BJ!
