### ISSUE TITLE
LinAlgError: cond is not defined on empty arrays

### ISSUE THREAD

**Issue by SpaceyCaseyLynn** [California-Planet-Search/radvel#314] opened 2020-05-21 09:47 UTC
I recently updated Radvel to 1.3.8, and now when I run the line "chains = radvel.mcmc(gppost,nrun=900,ensembles=3)" I get the following error "LinAlgError: cond is not defined on empty arrays". To the best of my knowledge gppost is not empty, and I'm able to make several different plots with it.

**Comment by bjfultn** [comment] 2020-05-21 15:45
Are you trying to start a new fit from scratch or just run/re-run MCMC on a previous run? If the latter, you might try starting it from scratch. 

Otherwise, I may have to try it out myself with your setup file and data. Please post if you are comfortable.

**Comment by SpaceyCaseyLynn** [comment] 2020-05-21 19:29
I've tried re-creating the gppost file a bunch of times so I don't think it's that. I'm running it in an ipynb, which it won't let me attach as a file so I'll email it to you.

**Comment by bjfultn** [comment] 2020-06-16 20:26
Has this been resolved? I never received the notebook file by e-mail.

**Comment by SpaceyCaseyLynn** [comment] 2020-06-22 20:32
It hasn't been resolved, I'll resend the notebook!

**Comment by SpaceyCaseyLynn** [comment] 2020-07-06 16:29
Hi Again,

I wanted to check in again and ask if you've had a chance to take a look at
this (and if you've received the jupyter notebook).

Best,
Casey

**Comment by bjfultn** [comment] 2020-07-20 22:10
It looks like I can get around this error by freeing up one or more of the GP parameters. So it seems like we can only run MCMC for GP posteriors when we have at least one of the GP parameters free. I'm not sure if this is a bug or a feature so I'm assigning to @sblunt to look into it.

**Comment by SpaceyCaseyLynn** [comment] 2020-07-20 22:39
Ohhh okay! I can let some parameters vary. Don't feel like you or @sblunt need to address this right away.

**Comment by sblunt** [comment] 2020-07-23 18:38
I'm having trouble reproducing this bug. I'm running the k2-131 GP example included in the radvel docs using the CLI. I can run the MAP fit and MCMC fit with no issue when I set all of the GP params to not vary. Would you all mind sharing the notebook containing the bug with me?

**Comment by bjfultn** [comment] 2020-07-23 18:43
I just forwarded Casey's notebook to you @sblunt

**Closed** 2021-03-03 23:11 UTC
Labels: bug, help wanted, priority:medium
