### ISSUE TITLE
sign conventions for radial velocity

### ISSUE THREAD

**Issue by petigura** [California-Planet-Search/radvel#51] opened 2016-12-31 20:11 UTC
In `rv_drive` we use the following formula for the RV of the star, which is consistent with the Murray and Correia chapter in the Seager's Exoplanets book:

```
 rv = k * ( np.cos( nu + om ) + e * np.cos( om ) ) 
```

`nu` is the true anomaly, and `om` is the arg of peri. This formula is defined for the positive z axis pointing at the observer. For example if `om = 0` the pericenter occurs at when the star moves from - to + z, which corresponds to maximum positive v_z.

However, we typically think of positive v_z as pointing away from the observer (red shifted). I believe that equating v_z to rv amounts to shifting om by 180 deg. This becomes the longitude of peri for the *planet* as opposed to the *star*. I think we should be explicit about what we mean by rv in the docs.

I'm in favor of returning -v_z as is done in TTVFast.

**Comment by awhoward** [comment] 2016-12-31 22:20
I suggest engaging Jason Wright and Geoff in an email conversation about this.  We discussed it thoroughly when Jason and I were developing rvlin and then later for a revision/erratum.  The historical aspects are important to recognize and to strive for consistency with.  I'll try to dig up some of that correspondence.

A key instance where you can check for consistency is in transiting planets where sin(om) and cos(om) are measured by transits and secondary eclipses. 

In [rvlin](http://iopscience.iop.org/article/10.1088/0067-0049/182/1/205/pdf), we wrote that the RVs of the star depend (Eq. 1) on the parameters of the planet, including omega of the planet.  We later recognized this mistake and released an [erratum](http://iopscience.iop.org/article/10.1088/0067-0049/205/2/22/pdf).

**Comment by bjfultn** [comment] 2017-12-07 01:18
Hey @awhoward does this orbital diagram look like it is labeled correctly (especially in the context of this omega confusion)? This orbit should have omega=45 degrees.

<img width="1898" alt="screen shot 2017-12-06 at 5 16 26 pm" src="https://user-images.githubusercontent.com/1724542/33693756-642a0cde-daa9-11e7-9148-39344666cf7d.png">

**Comment by bjfultn** [comment] 2017-12-12 20:40
I've now convinced myself that omega as we have it defined in radvel is the argument/longitude of periastron of the _star's_ orbit as I have it labeled i the figure.

I ran several fits for eccentric systems with RadVel, EXOFAST, and RVLIN and I get consistent values for omega. EXOFAST and RVLIN (via erratum) explicitly state that omega is the argument of periastron of the _star's_ orbit. Our equation for RV matches that of those codes exactly (see first post of this thread from @petigura):

EXOFAST:
<img width="625" alt="screen shot 2017-12-12 at 12 04 59 pm" src="https://user-images.githubusercontent.com/1724542/33905865-e65a10ca-df34-11e7-9428-7f3ceba17834.png">

RVLIN:
<img width="434" alt="screen shot 2017-12-12 at 12 08 15 pm" src="https://user-images.githubusercontent.com/1724542/33905993-669eb876-df35-11e7-8fe0-92e5939774e4.png">
(omega_j clarified via erratum to refer to the _star's_ motion caused by planet j as @awhoward mentioned)

As @petigura originally pointed out our equation is also consistent with the Murray and Correia chapter in the Exoplanets book.:
<img width="515" alt="screen shot 2017-12-12 at 12 17 17 pm" src="https://user-images.githubusercontent.com/1724542/33906377-9bab6b62-df36-11e7-8b8c-0fb12c137ec8.png">
In this equation it is a little unclear what omega is. However, it is first used in Section 5 which derives the motion of the _star_. In addition they explicitly define the argument of periastron of the planet's orbit as a different symbol (curly pi) in Section 2:
<img width="575" alt="screen shot 2017-12-12 at 12 23 53 pm" src="https://user-images.githubusercontent.com/1724542/33906696-8bd67f64-df37-11e7-9ea4-2b8befe63932.png">

Since RV is defined as dZ/dt with the Z axis pointing toward the observer I believe that the only thing incorrect about my figure is that RV>0 is actually dZ/dt > 0 which is a _blueshift_ and -RV is a _redshift_. The right panel will need to be flipped around to reflect this as well.

I will correct this on the Figure for the paper. @sealauren do you agree with this logic? Are you convinced yet that omega in RadVel is omega of the _star's_ orbit?

**Comment by bjfultn** [comment] 2017-12-21 22:42
@sealauren I believe @petigura and I figured out why we disagree on omega_star vs. omega_planet. 

Most observers define their axes such that +z is pointing _away_ from the observer and +RV = +dz/dt. This is the convention we have used (and will continue to use) in RadVel, RVLIN, EXOFAST, etc. This is the opposite convention of Deck and Agol (2014) in which they define +z as pointing _toward_ the observer and they state that +dz/dt = -RV. You follow the convention of Deck and Agol (2014) in the derivation you sent on slack. As you point out in your derivation if +dz/dt = -RV and you want these equations for RV to work then either omega must be omega_planet, or you must redefine +RV = +dz/dt.

It appears that the Murray and Correia derivation follows +z _toward_ the observer convention like Deck and Agol but they have a sign error that can be rectified in one of 3 ways:

1. Define the X, Y, Z coordinate system in Figure 7 to have Z pointing down (_away_ from observer).
2. Flip the sign of Equation (65)
3. Replace omega_star with omega_planet in Equation (65). @sealauren I think this is what you determined from your derivation.

Here is a new (hopefully final) version of the figure with things labeled correctly.

[phase_orbit.pdf](https://github.com/California-Planet-Search/radvel/files/1580861/phase_orbit.pdf)

**Comment by bjfultn** [comment] 2018-01-05 01:06
I believe we have worked this out now... closing

**Closed by bjfultn** 2018-01-05 01:06 UTC
Labels: priority:low

**Comment by j-faria** [comment] 2018-01-05 16:53
Hi @bjfultn, this diagram really helps to clarify the conventions used in the RV codes. Any chance the code you used to produce the figure can be made (or is already) available?

**Comment by bjfultn** [comment] 2018-01-05 18:05
@j-faria e-mail sent
