### ISSUE TITLE
import radvel failing

### ISSUE THREAD

**Issue by jvines** [California-Planet-Search/radvel#223] opened 2019-02-14 04:16 UTC
Hi all,

I'm using Python 2.7 in ubuntu 16.04.4 LTS and I get the following error when importing radvel:

ValueError                                Traceback (most recent call last)
<ipython-input-2-71291d062b04> in <module>()
----> 1 import radvel

/home/jose/anaconda2/lib/python2.7/site-packages/radvel/__init__.py in <module>()
      5 import nbsphinx  # producing ABC warning
      6 
----> 7 from .model import *
      8 from .likelihood import *
      9 from . import posterior

/home/jose/anaconda2/lib/python2.7/site-packages/radvel/model.py in <module>()
      2 from collections import OrderedDict
      3 
----> 4 from radvel import kepler
      5 from radvel.basis import Basis
      6 

/home/jose/anaconda2/lib/python2.7/site-packages/radvel/kepler.py in <module>()
      5 # Try to import Kepler's equation solver written in C
      6 try:
----> 7     from . import _kepler
      8     cext = True
      9 except ImportError:

__init__.pxd in init radvel._kepler()

ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject

I tried running conda update --all to no avail

**Comment by shashankdholakia** [comment] 2019-02-14 09:32
I'm also getting the same issue trying to import radvel into a python 3.6 jupyter notebook.

**Comment by bjfultn** [comment] 2019-02-14 13:13
Version 1.2.6 of RadVel? Try uninstalling RadVel then installing again. If that doesn’t work then try creating a fresh, empty conda environment and installing only what RadVel needs.

**Comment by jvines** [comment] 2019-02-14 15:16
I am using the latest version -- installed from pip.

I tried removing anaconda entirely and doing a clean install but the error still shows up

**Comment by jvines** [comment] 2019-02-14 15:46
I tried what @shashankdholakia  said and it worked for me. For some reason the pip installation doesn't work well

**Comment by bjfultn** [comment] 2019-02-14 16:11
Ok, glad you got it working. I’ll look into this when I get back next week. Version 1.2.5 introduced some installation bugs, which I thought I fixed in 1.2.6, but I guess not. Sounds like an issue with NumPy, scipy, or Cython.

**Comment by bjfultn** [comment] 2019-02-14 17:08
Could you both post the versions of NumPy that are currently installed in the environments in which the pip install fails? I think I need to update requirements.txt to require a newer (or specific) version of NumPy.

**Comment by shashankdholakia** [comment] 2019-02-15 04:41
I'm using numpy 1.14.2

**Comment by bjfultn** [comment] 2019-02-19 20:41
It looks like the issue is that Numpy>=1.16 is now required. I've updated the requirements.txt file and will release in version 1.2.7 (today).

**Closed by bjfultn** 2019-02-19 20:41 UTC
Labels: bug, priority:high
